name: demoapp-bdd-dump-test-run Scheduler
on:
  workflow_dispatch:
  # schedule:
  #   - cron: "*/5 * * * *"

env:
  RUN_FILE_NAME: run_terrafom.yml
  REPOSITORY: demoapp-bdd-dump-test
  ORGANISATION_NAME: FederationFrancaiseTennis

jobs:
  run-infra:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        env: ["dev", "test"]
    steps:
      - name: run infra
        run: |
          gh workflow run $RUN_FILE_NAME --repo "https://github.com/$ORGANISATION_NAME/$REPOSITORY_NAME" --ref ${{ matrix.env }}
